### ISSUE TITLE
Is this working plugin? 

### ISSUE THREAD

**Issue by skywinder** [amCap1712/listenbrainz-vlc#2]
Hi. looking how to integrate listenbrainz to vlc. is it working solution? can't figure out during lack of documantation

**Comment by amCap1712** [comment]
@skywinder Can you describe what you mean by integrating ? If you just want to use the plugin in VLC, see https://github.com/amCap1712/vlc-listenbrainz-plugin for a drop-in replacement. This repo is being used to develop an upstream patch of the plugin so that it can be sent to VideoLan for inclusion in future versions of VLC.

**Comment by skywinder** [comment]
yay, that what I'm looking for! Thank you for the quick response!
This was just first repo, that Google showed me by search: "listenbrainz vlc"

Cheers!

**Comment by amCap1712** [comment]
I will add a link to the out of tree plugin repo in the description of this repo to avoid confusing anyone.
